import FibreCampaign from "@/components/FibreCampaign";
import axios from "axios";
import Head from "next/head";
import { FC } from "react";

interface pageProps {}

const campaignsURL = process.env.API_URL || "";

const page: FC<pageProps> = async () => {
  const { data } = await axios.get(campaignsURL);

  return (
    <>
      <Head>
        <title>Mweb Demo</title>
        <meta name="description" content="Generated by Chris" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FibreCampaign campaigns={data.campaigns} />
    </>
  );
};

export default page;